import React, { createContext, useContext, useState } from "react";

const translations = {
  en: {
    english: "English",
    nepali: "नेपाली",
    loginRegister: "Login / Register",
    welcome: "Welcome to NayaMat",
    nayamat: "Your voice matters. Participate in a secure, transparent, and easy to use digital voting system. Democracy is now at your fingertips. Every vote counts, and every citizen has the power to shape the future. Join a community of responsible voters and help build a fairer, more inclusive, and connected society for everyone.",
    nayamatfooter: " © 2025 Nayamat Nepal. All Rights Reserved.",

    // Registration & Login
    registration: "Voter Registration",
    registrationSubtitle: "Register to participate in elections",
    candidateRegistration: "Candidate Registration",
    candidateRegistrationIntro: " Register as a candidate for upcoming elections. Fill in your details below.",
    personalInfo: "Personal Information",
    fullName: "Full Name",
    fullNamePlaceholder: "Enter your full name",
    dateOfBirth: "Date of Birth",
    email: "Email Address",
    emailPlaceholder: "Enter your email address",
    phone: "Phone Number",
    phonePlaceholder: "Enter your phone number",
    citizenshipNumber: "Citizenship Number",
    citizenshipPlaceholder: "Enter your citizenship number",
    password: "Password",
    passwordPlaceholder: "Enter your password",
    confirmPassword: "Confirm Password",
    confirmPasswordPlaceholder: "Re-enter your password",
    role: "Role",
    voter: "Voter",
    voters: "Voters",
    candidate: "Candidate",
    candidates: "Candidates",
    electoralCommittee: "Electoral Committee",
    admin: "Admin",
    register: "Register Now",
    alreadyRegistered: "Already registered?",
    login: "Login",
    back: "Back",
    idType: "ID Type",
    idPlaceholder: "Enter your ID number",
    citizenship: "Citizenship ID",
    national: "National ID",
    passport: "Passport",
    province: "Province",
    selectProvince: "Select Province",
    district: "District",
    districtPlaceholder: "Enter your district",
    ward: "Ward Number",
    wardPlaceholder: "Enter your Ward Number",
    voterId: "Voter ID",
    voterIdPlaceholder: "Enter your Voter ID",
    age: "Age",
    gender: "Gender",
    partyName: "Party Name",
    position: "Position",
    manifesto: "Manifesto / Campaign Promise",
    registerAsCandidate: "Register as Candidate",
    selectGender: "Select Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    home: "Home",
    aboutUs: "About Us",
    contactUs: "Contact Us",

    provinces: [
      "Province 1",
      "Madhesh Province",
      "Bagmati Province",
      "Gandaki Province",
      "Lumbini Province",
      "Karnali Province",
      "Sudurpashchim Province"
    ],

    aboutNayamat: "About NayaMat - A Digital Voting System",
    about: "Welcome to our Digital Voting System — a secure, transparent, and user-friendly platform designed to make voting simple, efficient, and trustworthy. Our mission is to revolutionize the way people participate in elections by combining modern technology with democratic values. Our system ensures that every individual's voice is heard, every vote is protected, and every result is delivered with integrity. We believe in empowering people through innovation because democracy thrives when it is accessible to all.",
    aim: "What We Aim For",
    aimPart: " We aim to eliminate barriers in traditional voting systems by ensuring accessibility, accuracy, and data integrity. Every vote matters, and we are committed to making sure each one is counted with the highest level of security and fairness. Our system is designed to promote trust, transparency, and inclusivity, empowering every voter to confidently take part in shaping a better future.",
    secure: "Secure",
    securePart: "Our platform uses encrypted data storage and verification methods to ensure your vote stays confidential.",
    fast: "Fast",
    fastPart: "Designed with speed and simplicity in mind, so you can cast your vote within seconds.",
    transparent: "Transparent",
    transparentPart: "Real-time vote tracking and clear results ensure full transparency throughout the election process.",
    future: "Together, we are shaping a smarter, fairer, and more connected democratic future.",

    ques: "Have questions, suggestions, or feedback? We would love to hear from you! Fill out the form below and we will get back to you as soon as possible.",
    name: "Name",
    namePlaceholder: "Enter your name",
    message: "Message",
    messagePlaceholder: "Enter your message",
    sendmsg: "Send Message",
    nayaMat: "NAYAMAT",
    nayaMatpart: "Welcome to Nayamat Nepal. We connect communities through accessible and transparent feedback and voting systems.",
    address: "Address",
    num: "+977 9812345678",
    intouch: "Get in Touch",
    add: "Kathmandu, Nepal",
    admin: "Admin",

    nayaMat: "NayaMat ",
    adminPanel: "Admin Panel",
    systemAdministrator: "System Administrator",
    logout: "Logout",
    dashboard: "Dashboard",
    total: "Total",
    moreInfo: "More Info →",
    voted: "Voted",
    reset: "Reset",
    search: "Search",
    votes: "Votes",
    list: "List",
    addVoter: "Add Voter",
    addNewCandidate: "Add New Candidate",

    close: "✖ Close",
    update: "✔ Update",
    save: "Save",
    addnew: "+ Add New",
    bio: "Bio",
    bioPlaceholder: "Enter your bio",
    photo: "Photo",
    action: "Action",
    edit: "Edit",
    delete: "Delete",
    uploadPhoto: "Upload Photo",
    choosephoto: "Choose Photo",
    profilePhoto: "Profile Photo",
  },

 np: {
    english: "अंग्रेजी",
    nepali: "नेपाली",
    loginRegister: "लगइन / दर्ता",
    welcome: "नयाँमतमा स्वागत छ",
    nayamat: "तपाईंको आवाज महत्वपूर्ण छ। सुरक्षित, पारदर्शी, र प्रयोग गर्न सजिलो डिजिटल मतदान प्रणालीमा भाग लिनुहोस्। लोकतन्त्र अब तपाईंको औंलाको टोकाइमा। प्रत्येक मत गन्तव्यमा गयो र प्रत्येक नागरिकले भविष्य निर्माण गर्ने शक्ति राख्दछ। जिम्मेवार मतदाताहरूको समुदायमा सामेल हुनुहोस् र सबैका लागि न्यायोचित, समावेशी, र जडित समाज निर्माणमा योगदान दिनुहोस्।",
    nayamatfooter: " © 2025 नयाँमत नेपाल। सर्वाधिकार सुरक्षित।",

    // Registration & Login
    registration: "मतदाता दर्ता",
    registrationSubtitle: "निर्वाचनमा भाग लिन दर्ता गर्नुहोस्",
    candidateRegistration: "उम्मेदवार दर्ता",
    candidateRegistrationIntro: "आगामी निर्वाचनका लागि उम्मेदवारको रूपमा दर्ता गर्नुहोस्। तल आफ्नो विवरण भर्नुहोस्।",
    personalInfo: "व्यक्तिगत जानकारी",
    fullName: "पूरा नाम",
    fullNamePlaceholder: "तपाईंको पूरा नाम प्रविष्ट गर्नुहोस्",
    dateOfBirth: "जन्म मिति",
    email: "इमेल ठेगाना",
    emailPlaceholder: "तपाईंको इमेल ठेगाना प्रविष्ट गर्नुहोस्",
    phone: "फोन नम्बर",
    phonePlaceholder: "तपाईंको फोन नम्बर प्रविष्ट गर्नुहोस्",
    citizenshipNumber: "नागरिकता नम्बर",
    citizenshipPlaceholder: "तपाईंको नागरिकता नम्बर प्रविष्ट गर्नुहोस्",
    password: "पासवर्ड",
    passwordPlaceholder: "तपाईंको पासवर्ड प्रविष्ट गर्नुहोस्",
    confirmPassword: "पासवर्ड पुष्टि गर्नुहोस्",
    confirmPasswordPlaceholder: "फेरि पासवर्ड प्रविष्ट गर्नुहोस्",
    role: "भूमिका",
    voter: "मतदाता",
    voters: "मतदाताहरू",
    candidate: "उम्मेदवार",
    candidates: "उम्मेदवारहरू",
    electoralCommittee: "निर्वाचन समिति",
    admin: "प्रशासक",
    register: "अब दर्ता गर्नुहोस्",
    alreadyRegistered: "पहिले नै दर्ता भइसकेको?",
    login: "लगइन",
    back: "फिर्ता",
    idType: "पहिचान प्रकार",
    idPlaceholder: "तपाईंको ID नम्बर प्रविष्ट गर्नुहोस्",
    citizenship: "नागरिकता ID",
    national: "राष्ट्रिय ID",
    passport: "पासपोर्ट",
    province: "प्रदेश",
    selectProvince: "प्रदेश छान्नुहोस्",
    district: "जिल्ला",
    districtPlaceholder: "तपाईंको जिल्ला प्रविष्ट गर्नुहोस्",
    ward: "वडा नम्बर",
    wardPlaceholder: "तपाईंको वडा नम्बर प्रविष्ट गर्नुहोस्",
    voterId: "मतदाता ID",
    voterIdPlaceholder: "तपाईंको मतदाता ID प्रविष्ट गर्नुहोस्",
    age: "उमेर",
    gender: "लिङ्ग",
    partyName: "पार्टी नाम",
    position: "पद",
    manifesto: "घोषणा / चुनावी वाचा",
    registerAsCandidate: "उम्मेदवारको रूपमा दर्ता गर्नुहोस्",
    selectGender: "लिङ्ग छान्नुहोस्",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    home: "गृहपृष्ठ",
    aboutUs: "हाम्रो बारेमा",
    contactUs: "सम्पर्क गर्नुहोस्",

    provinces: [
      "प्रदेश १",
      "मधेश प्रदेश",
      "बागमती प्रदेश",
      "गण्डकी प्रदेश",
      "लुम्बिनी प्रदेश",
      "कर्णाली प्रदेश",
      "सुदूरपश्चिम प्रदेश"
    ],

    aboutNayamat: "नयाँमत - डिजिटल मतदान प्रणालीको बारेमा",
    about: "हाम्रो डिजिटल मतदान प्रणालीमा स्वागत छ — सुरक्षित, पारदर्शी, र प्रयोगकर्ता मैत्री प्लेटफर्म, जसले मतदान प्रक्रियालाई सरल, छिटो, र भरपर्दो बनाउँछ। हाम्रो मिशन आधुनिक प्रविधि र लोकतान्त्रिक मूल्यहरूलाई संयोजन गरी मानिसहरूले निर्वाचनमा सहज भाग लिन सकून् भन्ने सुनिश्चित गर्नु हो। हाम्रो प्रणालीले प्रत्येक व्यक्तिको आवाज सुन्ने, प्रत्येक मत सुरक्षित गर्ने, र परिणाम इमान्दारिपूर्वक प्रस्तुत गर्ने सुनिश्चित गर्दछ। हामी नवप्रवर्तन मार्फत जनतालाई सशक्त बनाउने विश्वास गर्छौं किनभने लोकतन्त्र सबैका लागि पहुँचयोग्य हुँदा फस्टाउँछ।",
    aim: "हामी के लक्ष्य राख्छौं",
    aimPart: "हामी पारम्परिक मतदान प्रणालीमा रहेका बाधाहरू हटाउन, पहुँचयोग्यता, शुद्धता, र डाटाको इमान्दारी सुनिश्चित गर्न चाहन्छौं। प्रत्येक मत महत्वपूर्ण छ, र हामी सुनिश्चित गर्न प्रतिबद्ध छौं कि प्रत्येक मत उच्च सुरक्षा र निष्पक्षताका साथ गणना गरिन्छ। हाम्रो प्रणालीले विश्वास, पारदर्शिता, र समावेशिता बढाउन डिजाइन गरिएको हो, जसले प्रत्येक मतदातालाई भविष्य निर्माणमा आत्मविश्वासका साथ भाग लिन सक्षम बनाउँछ।",
    secure: "सुरक्षित",
    securePart: "हाम्रो प्लेटफर्मले एनक्रिप्टेड डाटा भण्डारण र प्रमाणीकरण विधिहरू प्रयोग गर्छ जसले तपाईंको मत गोप्य रहोस् सुनिश्चित गर्छ।",
    fast: "छिटो",
    fastPart: "छिटो र सरल बनाउन डिजाइन गरिएको, ताकि तपाईं केही सेकेन्डमा मतदान गर्न सक्नुहोस्।",
    transparent: "पारदर्शी",
    transparentPart: "रियल-टाइम मत ट्र्याकिङ र स्पष्ट परिणामले सम्पूर्ण निर्वाचन प्रक्रियामा पूर्ण पारदर्शिता सुनिश्चित गर्दछ।",
    future: "सँगै, हामी स्मार्ट, निष्पक्ष, र जडित लोकतान्त्रिक भविष्य निर्माण गर्दैछौं।",

    ques: "सवाल, सुझाव, वा प्रतिक्रिया छ? कृपया तलको फारम भर्नुहोस्, हामी सकेसम्म चाँडो तपाईंलाई प्रतिक्रिया दिनेछौं।",
    name: "नाम",
    namePlaceholder: "तपाईंको नाम प्रविष्ट गर्नुहोस्",
    message: "सन्देश",
    messagePlaceholder: "तपाईंको सन्देश प्रविष्ट गर्नुहोस्",
    sendmsg: "सन्देश पठाउनुहोस्",
    nayaMat: "नयाँमत",
    nayaMatpart: "नयाँमत नेपालमा स्वागत छ। हामी पहुँचयोग्य र पारदर्शी प्रतिक्रिया र मतदान प्रणालीमार्फत समुदायहरूलाई जडान गर्छौं।",
    address: "ठेगाना",
    num: "+977 9812345678",
    intouch: "सम्पर्कमा रहनुहोस्",
    add: "काठमाडौं, नेपाल",
    admin: "प्रशासक",

    adminPanel: "प्रशासक प्यानल",
    systemAdministrator: "प्रणाली प्रशासक",
    logout: "लगआउट",
    dashboard: "ड्यासबोर्ड",
    total: "कुल",
    moreInfo: "थप जानकारी →",
    voted: "मत दिएको",
    reset: "रिसेट",
    search: "खोज्नुहोस्",
    votes: "मतहरू",
    list: "सूची",
    addVoter: "मतदाता थप्नुहोस्",
    addNewCandidate: "नयाँ उम्मेदवार थप्नुहोस्",

    close: "✖ बन्द गर्नुहोस्",
    update: "✔ अपडेट गर्नुहोस्",
    save: "सेभ गर्नुहोस्",
    addnew: "+ नयाँ थप्नुहोस्",
    bio: "बायो",
    bioPlaceholder: "तपाईंको बायो प्रविष्ट गर्नुहोस्",
    photo: "फोटो",
    action: "कार्य",
    edit: "सम्पादन",
    delete: "हटाउनुहोस्",
    uploadPhoto: "फोटो अपलोड गर्नुहोस्",
    choosephoto: "फोटो चयन गर्नुहोस्",
    profilePhoto: "प्रोफाइल फोटो",
}



};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState("en");

  const t = (key) => {
    const value = translations[language][key];
    return value !== undefined ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
